/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrakritiFi } from "./PrakritiFi";
export * as factories from "./factories";
export { PrakritiFi__factory } from "./factories/PrakritiFi__factory";
