/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PrakritiFiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fundVault"
      | "mintGroundTruthCredential"
      | "owner"
      | "triggerInsurancePayout"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CredentialMinted" | "InsurancePayout"
  ): EventFragment;

  encodeFunctionData(functionFragment: "fundVault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintGroundTruthCredential",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "triggerInsurancePayout",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "fundVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintGroundTruthCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "triggerInsurancePayout",
    data: BytesLike
  ): Result;
}

export namespace CredentialMintedEvent {
  export type InputTuple = [farmer: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [farmer: string, timestamp: bigint];
  export interface OutputObject {
    farmer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InsurancePayoutEvent {
  export type InputTuple = [
    farmer: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [farmer: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    farmer: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrakritiFi extends BaseContract {
  connect(runner?: ContractRunner | null): PrakritiFi;
  waitForDeployment(): Promise<this>;

  interface: PrakritiFiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fundVault: TypedContractMethod<[], [void], "payable">;

  mintGroundTruthCredential: TypedContractMethod<
    [farmer: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  triggerInsurancePayout: TypedContractMethod<
    [farmer: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fundVault"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "mintGroundTruthCredential"
  ): TypedContractMethod<[farmer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "triggerInsurancePayout"
  ): TypedContractMethod<
    [farmer: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CredentialMinted"
  ): TypedContractEvent<
    CredentialMintedEvent.InputTuple,
    CredentialMintedEvent.OutputTuple,
    CredentialMintedEvent.OutputObject
  >;
  getEvent(
    key: "InsurancePayout"
  ): TypedContractEvent<
    InsurancePayoutEvent.InputTuple,
    InsurancePayoutEvent.OutputTuple,
    InsurancePayoutEvent.OutputObject
  >;

  filters: {
    "CredentialMinted(address,uint256)": TypedContractEvent<
      CredentialMintedEvent.InputTuple,
      CredentialMintedEvent.OutputTuple,
      CredentialMintedEvent.OutputObject
    >;
    CredentialMinted: TypedContractEvent<
      CredentialMintedEvent.InputTuple,
      CredentialMintedEvent.OutputTuple,
      CredentialMintedEvent.OutputObject
    >;

    "InsurancePayout(address,uint256,uint256)": TypedContractEvent<
      InsurancePayoutEvent.InputTuple,
      InsurancePayoutEvent.OutputTuple,
      InsurancePayoutEvent.OutputObject
    >;
    InsurancePayout: TypedContractEvent<
      InsurancePayoutEvent.InputTuple,
      InsurancePayoutEvent.OutputTuple,
      InsurancePayoutEvent.OutputObject
    >;
  };
}
